# Generated by Django 5.0.3 on 2024-03-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='itemCode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
