# Generated by Django 5.0.3 on 2024-03-14 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServiceApp', '0002_orderitem_itemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='itemCode',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
