# Generated by Django 5.0.3 on 2024-03-14 08:06

import OrderServiceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServiceApp', '0003_orderitem_description_alter_orderitem_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='itemCode',
            field=models.CharField(blank=True, default=OrderServiceApp.models.default_function, editable=False, max_length=14),
        ),
    ]
