# Generated by Django 5.0.3 on 2024-03-17 15:08

import OrderServiceApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServiceApp', '0004_alter_orderitem_itemcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('itemCode', models.CharField(blank=True, default=OrderServiceApp.models.default_function, editable=False, max_length=14)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='itemCode',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderServiceApp.product'),
        ),
    ]
