# Generated by Django 5.0.3 on 2024-03-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderServiceApp', '0005_product_remove_orderitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
